openapi: 3.0.0
info:
  title: Auth Module API
  version: 1.0.0
  description: API endpoints for authentication and API key management
paths:
  /v1/api-keys/create:
    post:
      summary: Create new API key
      description: Creates a new API key for the authenticated user
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name for the API key
                expiresInDays:
                  type: integer
                  description: Number of days until the API key expires
      responses:
        '201':
          description: API key created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  apiKey:
                    type: string
                    description: The API key (only returned once)
                  id:
                    type: string
                    format: uuid
                  key_prefix:
                    type: string
                  name:
                    type: string
                  expires_at:
                    type: string
                    format: date-time
                  created_at:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /v1/api-keys/revoke:
    delete:
      summary: Revoke API key
      description: Revokes an API key based on its prefix
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                keyPrefix:
                  type: string
                  description: Prefix of the API key to revoke
              required:
                - keyPrefix
      responses:
        '200':
          description: API key revoked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: API key not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /v1/api-keys:
    get:
      summary: List API keys
      description: Lists all API keys for the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of API keys
          content:
            application/json:
              schema:
                type: object
                properties:
                  apiKeys:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        key_prefix:
                          type: string
                        name:
                          type: string
                        expires_at:
                          type: string
                          format: date-time
                        created_at:
                          type: string
                          format: date-time
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT