openapi: 3.0.0
info:
  title: Core Module API
  version: 1.0.0
  description: Core API endpoints for health checks and version information
paths:
  /v1/health:
    get:
      summary: Health check
      description: Checks the health of all services
      responses:
        '200':
          description: Health check successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok, degraded, error]
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string
                  environment:
                    type: string
                  services:
                    type: object
                    properties:
                      database:
                        type: object
                        properties:
                          status:
                            type: string
                            enum: [ok, error]
                          latency:
                            type: number
                      auth:
                        type: object
                        properties:
                          status:
                            type: string
                            enum: [ok, error]
                      storage:
                        type: object
                        properties:
                          status:
                            type: string
                            enum: [ok, error]
        '500':
          description: Health check failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
  
  /v1/version:
    get:
      summary: Version information
      description: Gets the version information for the API
      responses:
        '200':
          description: Version information
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                  buildNumber:
                    type: string
                  buildDate:
                    type: string
                    format: date-time
                  environment:
                    type: string
                  commit:
                    type: string

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string